name: Deploy to production

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Clone repo
        run: |
          rm -rf site
          git clone --depth=1 https://vnprc:${{ secrets.CLONE_TOKEN }}@forge.anarch.diy/vnprc/hashpool-website.git site

      - name: Install Zola
        run: |
          ZOLA_VERSION="v0.19.2"
          curl -sSL "https://github.com/getzola/zola/releases/download/$ZOLA_VERSION/zola-$ZOLA_VERSION-x86_64-unknown-linux-gnu.tar.gz" \
            | tar -xz -C /tmp

      - name: Build site
        run: cd site && /tmp/zola build

      - name: Deploy
        run: rsync -av --delete site/public/ /var/www/hashpool/
